// vscode — generate a .vscode/tasks.json for any project so Claude Carry is
// drivable from the Command Palette (Ctrl+Shift+P -> Tasks: Run Task). The
// tasks call this repo's carry.cmd by ABSOLUTE path and queue for the target
// workspace, so they work from a project that isn't the Claude Carry repo.
//
// Non-destructive: if the target already has a tasks.json, we write to
// carry.tasks.json instead and tell the user to merge — never overwrite.

import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const NQ_CMD = join(REPO_ROOT, 'bin', 'carry.cmd');

function tasksJson(nqCmd) {
  const task = (label, args, extra = {}) => ({
    label,
    type: 'shell',
    command: nqCmd,
    args,
    problemMatcher: [],
    ...extra,
  });
  return {
    version: '2.0.0',
    _comment: 'Claude Carry tasks — generated by `carry install-vscode`. Run via Ctrl+Shift+P -> Tasks: Run Task.',
    tasks: [
      task('Claude Carry: Add task', ['add', '${input:taskPrompt}', '--cwd', '${workspaceFolder}']),
      task('Claude Carry: Add task (plan-first)', ['add', '${input:taskPrompt}', '--plan', '--cwd', '${workspaceFolder}']),
      task('Claude Carry: Status', ['status']),
      task('Claude Carry: Parked (needs approval)', ['parked']),
      task('Claude Carry: Approve task', ['approve', '${input:taskId}']),
      task('Claude Carry: Morning report', ['report']),
      task('Claude Carry: Run the night shift', ['run'], { isBackground: true }),
      task('Claude Carry: Doctor (health check)', ['doctor', '--smoke']),
    ],
    inputs: [
      { id: 'taskPrompt', type: 'promptString', description: 'What should Claude Carry do? (the task prompt)' },
      { id: 'taskId', type: 'promptString', description: 'Task id (e.g. t1)' },
    ],
  };
}

export function installVscode(targetDir) {
  if (!existsSync(NQ_CMD)) throw new Error(`carry.cmd not found at ${NQ_CMD}`);
  const vscodeDir = join(targetDir, '.vscode');
  mkdirSync(vscodeDir, { recursive: true });
  const json = JSON.stringify(tasksJson(NQ_CMD), null, 2) + '\n';
  const primary = join(vscodeDir, 'tasks.json');
  if (existsSync(primary)) {
    const alt = join(vscodeDir, 'carry.tasks.json');
    writeFileSync(alt, json);
    return { wrote: alt, merged: false, note: 'tasks.json already exists — wrote Claude Carry tasks to carry.tasks.json; merge its "tasks" and "inputs" arrays into your tasks.json' };
  }
  writeFileSync(primary, json);
  return { wrote: primary, merged: true };
}
